// ============================================================================
//  data.js  —  Solar System dataset
//  * Keplerian orbital elements (J2000.0 epoch, from NASA/JPL) for accurate
//    relative positions at any simulated date.
//  * Physical & descriptive data shown in the info panel (all in English).
//  Angles are in degrees, distances in AU, periods in days, radius relative
//  to Earth (Earth = 1).  Rotation in hours (negative = retrograde spin).
// ============================================================================

// Display tuning ------------------------------------------------------------
export const CONFIG = {
  EARTH_RADIUS_UNITS: 1.6,   // scene units for 1 Earth radius (body sizes)
  SUN_RADIUS_UNITS:   22,    // Sun's drawn radius in the COMPRESSED view only
                             // (true scale would be 109.2 x Earth — see below)
  // Distance mapping (AU -> scene units). Two regimes:
  //   visual              : compressed so every planet is visible together
  //   realistic/accurate  : TRUE to scale — bodies and the distances between
  //                         them share one ruler, so the Sun is a dot and the
  //                         planets are specks lost in mostly-empty space.
  DIST_VISUAL_K:   60,
  DIST_VISUAL_EXP: 0.62,
  // True scene-units per AU. Body radii use EARTH_RADIUS_UNITS (1.6 units per
  // Earth radius); to keep ONE consistent ruler, an AU must use the same scale.
  // 1 Earth radius = 6,371 km and 1 AU = 149,597,871 km, so 1 AU = 23,481 Earth
  // radii  ->  23,481 x 1.6 = 37,569.6 scene units per AU. This makes the Sun's
  // true diameter span exactly ~1/107 of Earth's orbit, as it does in reality.
  DIST_REAL_K:     37569.6,
  // Physical constants — used to put moons (any distance given in km) on the
  // SAME true-scale ruler as the planets: 1 scene unit = 6371 / 1.6 ≈ 3,981.9 km.
  // (DIST_REAL_K above equals EARTH_RADIUS_UNITS * KM_PER_AU / KM_PER_EARTH_RADIUS.)
  KM_PER_EARTH_RADIUS: 6371,
  KM_PER_AU:           149597870.7,
  J2000_JD: 2451545.0,       // Julian Date of the J2000 epoch
};

// Secular rates of the Keplerian elements, per Julian century, w.r.t. the mean
// ecliptic & equinox of J2000 — NASA/JPL "Approximate Positions of the Planets"
// Table 1 (valid 1800-2050) for the eight planets; Pluto from the long-term set.
// Order matches the elements: a (AU), e, i (deg), L mean-longitude (deg),
// wbar longitude-of-perihelion (deg), om longitude-of-ascending-node (deg).
export const RATES = {
  mercury: { a: 0.00000037, e: 0.00001906, i: -0.00594749, L: 149472.67411175, wbar: 0.16047689, om: -0.12534081 },
  venus:   { a: 0.00000390, e: -0.00004107, i: -0.00078890, L: 58517.81538729, wbar: 0.00268329, om: -0.27769418 },
  earth:   { a: 0.00000562, e: -0.00004392, i: -0.01294668, L: 35999.37244981, wbar: 0.32327364, om: 0.0 },
  mars:    { a: 0.00001847, e: 0.00007882, i: -0.00813131, L: 19140.30268499, wbar: 0.44441088, om: -0.29257343 },
  jupiter: { a: -0.00011607, e: -0.00013253, i: -0.00183714, L: 3034.74612775, wbar: 0.21252668, om: 0.20469106 },
  saturn:  { a: -0.00125060, e: -0.00050991, i: 0.00193609, L: 1222.49362201, wbar: -0.41897216, om: -0.28867794 },
  uranus:  { a: -0.00196176, e: -0.00004397, i: -0.00242939, L: 428.48202785, wbar: 0.40805281, om: 0.04240589 },
  neptune: { a: 0.00026291, e: 0.00005105, i: 0.00035372, L: 218.45945325, wbar: -0.32241464, om: -0.00508664 },
  pluto:   { a: -0.00031596, e: 0.00005170, i: 0.00004818, L: 145.20780515, wbar: -0.04062942, om: -0.01183482 },
};

// The Sun -------------------------------------------------------------------
export const SUN = {
  id: 'sun', name: 'Sun', type: 'Star',
  texture: 'textures/sun.jpg',
  radiusEarth: 109.2,
  rotationHours: 609.12,     // ~25.4 days at equator
  axialTilt: 7.25,
  color: 0xffcc55,
  description:
    'The Sun is the star at the heart of the Solar System — a near-perfect ' +
    'sphere of hot plasma that contains 99.86% of the system\'s total mass. ' +
    'Energy generated by nuclear fusion in its core radiates outward and ' +
    'sustains nearly all life on Earth.',
  info: {
    'Type': 'G2V Yellow Dwarf Star',
    'Diameter': '1,392,700 km (109 × Earth)',
    'Mass': '1.989 × 10³⁰ kg (333,000 × Earth)',
    'Surface gravity': '274 m/s² (28 × Earth)',
    'Mean density': '1.41 g/cm³',
    'Core temperature': '~15,000,000 °C',
    'Surface temperature': '~5,500 °C',
    'Rotation period': '25.4 days (equator)',
    'Composition': '73% Hydrogen, 25% Helium',
    'Age': '~4.6 billion years',
  },
  facts: [
    'About 1.3 million Earths could fit inside the Sun.',
    'Light from the Sun takes about 8 minutes 20 seconds to reach Earth.',
    'The Sun fuses ~600 million tonnes of hydrogen into helium every second.',
    'It is roughly halfway through its ~10-billion-year main-sequence life.',
    'The Sun\'s outer atmosphere (the corona) is far hotter than its surface.',
  ],
};

// Planets & dwarf planets ---------------------------------------------------
// Orbital elements: a (AU), e, i (deg), om = Ω longitude of ascending node,
// wbar = ϖ longitude of perihelion, L0 = mean longitude at J2000 (deg).
export const PLANETS = [
  {
    id: 'mercury', name: 'Mercury', type: 'Terrestrial Planet',
    texture: 'textures/mercury.jpg', color: 0xa9a9a9,
    radiusEarth: 0.383, axialTilt: 0.034, rotationHours: 1407.6,
    a: 0.38709927, e: 0.20563593, i: 7.00497902,
    om: 48.33076593, wbar: 77.45779628, L0: 252.25032350, periodDays: 87.969,
    description:
      'Mercury is the smallest planet and the closest to the Sun. It has no ' +
      'substantial atmosphere, so its cratered surface swings between ' +
      'extremes of heat and cold. A year on Mercury lasts just 88 Earth days.',
    info: {
      'Diameter': '4,879 km',
      'Mass': '3.30 × 10²³ kg (0.055 × Earth)',
      'Surface gravity': '3.7 m/s²',
      'Mean density': '5.43 g/cm³',
      'Distance from Sun': '57.9 million km (0.39 AU)',
      'Orbital period': '88 Earth days',
      'Rotation period': '58.6 Earth days',
      'Axial tilt': '0.03°',
      'Orbital velocity': '47.4 km/s',
      'Eccentricity': '0.206',
      'Orbital inclination': '7.0°',
      'Surface temp.': '-173 °C to 427 °C',
      'Moons': '0',
      'Atmosphere': 'Negligible (trace Na, O, H)',
    },
    facts: [
      'Mercury has the most eccentric (least circular) orbit of any planet.',
      'A single solar day on Mercury (sunrise to sunrise) lasts 176 Earth days.',
      'Despite being closest to the Sun, it is not the hottest planet — Venus is.',
      'Its iron core makes up about 85% of its radius.',
      'Mercury is shrinking as its interior cools, forming giant cliffs.',
    ],
  },
  {
    id: 'venus', name: 'Venus', type: 'Terrestrial Planet',
    texture: 'textures/venus_surface.jpg', color: 0xe6c27a,
    atmosphereTexture: 'textures/venus_atmosphere.jpg',
    radiusEarth: 0.949, axialTilt: 177.36, rotationHours: -5832.5,
    a: 0.72333566, e: 0.00677672, i: 3.39467605,
    om: 76.67984255, wbar: 131.60246718, L0: 181.97909950, periodDays: 224.701,
    description:
      'Venus is the second planet and the hottest in the Solar System, wrapped ' +
      'in a thick carbon-dioxide atmosphere that traps heat in a runaway ' +
      'greenhouse effect. It spins backwards, so the Sun rises in the west.',
    info: {
      'Diameter': '12,104 km',
      'Mass': '4.87 × 10²⁴ kg (0.815 × Earth)',
      'Surface gravity': '8.87 m/s²',
      'Mean density': '5.24 g/cm³',
      'Distance from Sun': '108.2 million km (0.72 AU)',
      'Orbital period': '225 Earth days',
      'Rotation period': '243 Earth days (retrograde)',
      'Axial tilt': '177.4°',
      'Orbital velocity': '35.0 km/s',
      'Eccentricity': '0.007',
      'Orbital inclination': '3.4°',
      'Surface temp.': '~465 °C (average)',
      'Moons': '0',
      'Atmosphere': '96.5% CO₂, 3.5% N₂',
    },
    facts: [
      'Venus is the hottest planet — hot enough to melt lead at its surface.',
      'Its surface pressure is about 92 times that of Earth at sea level.',
      'A day on Venus is longer than its year.',
      'It rotates in the opposite direction to most planets (retrograde).',
      'Venus is the brightest natural object in our night sky after the Moon.',
    ],
  },
  {
    id: 'earth', name: 'Earth', type: 'Terrestrial Planet',
    texture: 'textures/earth_day.jpg', color: 0x2f6dd0,
    nightTexture: 'textures/earth_night.jpg',
    cloudsTexture: 'textures/earth_clouds.jpg',
    specularTexture: 'textures/earth_specular.png',   // SSS water mask → precise ocean glint
    radiusEarth: 1.0, axialTilt: 23.44, rotationHours: 23.9345,
    a: 1.00000261, e: 0.01671123, i: -0.00001531,
    om: 0.0, wbar: 102.93768193, L0: 100.46457166, periodDays: 365.256,
    description:
      'Earth is our home — the only world known to harbour life. Liquid water ' +
      'covers about 71% of its surface, and a protective magnetic field and ' +
      'atmosphere shield it from harmful solar radiation.',
    info: {
      'Diameter': '12,742 km',
      'Mass': '5.97 × 10²⁴ kg',
      'Surface gravity': '9.81 m/s²',
      'Mean density': '5.51 g/cm³ (densest planet)',
      'Distance from Sun': '149.6 million km (1 AU)',
      'Orbital period': '365.26 days',
      'Rotation period': '23.93 hours',
      'Axial tilt': '23.44°',
      'Orbital velocity': '29.8 km/s',
      'Eccentricity': '0.017',
      'Orbital inclination': '0.0°',
      'Surface temp.': '-88 °C to 58 °C',
      'Moons': '1 (the Moon)',
      'Atmosphere': '78% N₂, 21% O₂',
    },
    facts: [
      'Earth is the densest planet in the Solar System.',
      'It is the only planet not named after a Greek or Roman deity.',
      'Earth\'s axial tilt gives us the seasons.',
      'The Moon is gradually drifting away from Earth (~3.8 cm per year).',
      '70% of Earth\'s surface is covered by oceans.',
    ],
  },
  {
    id: 'mars', name: 'Mars', type: 'Terrestrial Planet',
    texture: 'textures/mars.jpg', color: 0xc1440e,
    radiusEarth: 0.532, axialTilt: 25.19, rotationHours: 24.6229,
    a: 1.52371034, e: 0.09339410, i: 1.84969142,
    om: 49.55953891, wbar: -23.94362959, L0: -4.55343205, periodDays: 686.980,
    description:
      'Mars, the "Red Planet", owes its colour to iron-oxide dust. It hosts ' +
      'the tallest volcano (Olympus Mons) and one of the largest canyons ' +
      '(Valles Marineris) in the Solar System, and shows clear signs that ' +
      'liquid water once flowed across its surface.',
    info: {
      'Diameter': '6,779 km',
      'Mass': '6.42 × 10²³ kg (0.107 × Earth)',
      'Surface gravity': '3.72 m/s²',
      'Mean density': '3.93 g/cm³',
      'Distance from Sun': '227.9 million km (1.52 AU)',
      'Orbital period': '687 Earth days',
      'Rotation period': '24.6 hours',
      'Axial tilt': '25.19°',
      'Orbital velocity': '24.1 km/s',
      'Eccentricity': '0.093',
      'Orbital inclination': '1.85°',
      'Surface temp.': '-153 °C to 20 °C',
      'Moons': '2 (Phobos & Deimos)',
      'Atmosphere': '95% CO₂ (very thin)',
    },
    facts: [
      'Olympus Mons is ~22 km tall — nearly three times the height of Everest.',
      'Mars has the largest dust storms in the Solar System, which can engulf the planet.',
      'A Martian day ("sol") is just 40 minutes longer than an Earth day.',
      'Its two moons, Phobos and Deimos, are likely captured asteroids.',
      'Mars has polar ice caps made of water and frozen carbon dioxide.',
    ],
  },
  {
    id: 'jupiter', name: 'Jupiter', type: 'Gas Giant',
    texture: 'textures/jupiter.jpg', color: 0xd8ca9d,
    radiusEarth: 11.21, axialTilt: 3.13, rotationHours: 9.925,
    a: 5.20288700, e: 0.04838624, i: 1.30439695,
    om: 100.47390909, wbar: 14.72847983, L0: 34.39644051, periodDays: 4332.589,
    description:
      'Jupiter is the largest planet — a gas giant more than twice as massive ' +
      'as all the other planets combined. Its swirling cloud bands and the ' +
      'centuries-old Great Red Spot, a storm wider than Earth, dominate its ' +
      'appearance.',
    info: {
      'Diameter': '139,820 km',
      'Mass': '1.90 × 10²⁷ kg (318 × Earth)',
      'Surface gravity': '24.79 m/s²',
      'Mean density': '1.33 g/cm³',
      'Distance from Sun': '778.5 million km (5.20 AU)',
      'Orbital period': '11.86 Earth years',
      'Rotation period': '9.9 hours (fastest)',
      'Axial tilt': '3.13°',
      'Orbital velocity': '13.1 km/s',
      'Eccentricity': '0.049',
      'Orbital inclination': '1.30°',
      'Cloud-top temp.': '~-145 °C',
      'Moons': '101 known',
      'Atmosphere': '90% H₂, 10% He',
    },
    facts: [
      'Jupiter has the shortest day of any planet — under 10 hours.',
      'The Great Red Spot is a storm that has raged for at least 350 years.',
      'Its four largest moons were discovered by Galileo in 1610.',
      'Jupiter has a faint ring system, discovered by Voyager 1 in 1979.',
      'It has the strongest magnetic field of any planet.',
    ],
  },
  {
    id: 'saturn', name: 'Saturn', type: 'Gas Giant',
    texture: 'textures/saturn.jpg', color: 0xe3d9a6,
    radiusEarth: 9.45, axialTilt: 26.73, rotationHours: 10.656,
    ring: { inner: 1.2, outer: 2.3, texture: 'textures/saturn_ring.png' },
    a: 9.53667594, e: 0.05386179, i: 2.48599187,
    om: 113.66242448, wbar: 92.59887831, L0: 49.95424423, periodDays: 10759.22,
    description:
      'Saturn is the second-largest planet, famous for its spectacular ring ' +
      'system made of countless icy and rocky particles. It is the least ' +
      'dense planet — so light it would float in water, if a bath that big existed.',
    info: {
      'Diameter': '116,460 km',
      'Mass': '5.68 × 10²⁶ kg (95 × Earth)',
      'Surface gravity': '10.44 m/s²',
      'Mean density': '0.69 g/cm³ (least dense)',
      'Distance from Sun': '1,434 million km (9.54 AU)',
      'Orbital period': '29.45 Earth years',
      'Rotation period': '10.7 hours',
      'Axial tilt': '26.73°',
      'Orbital velocity': '9.7 km/s',
      'Eccentricity': '0.054',
      'Orbital inclination': '2.49°',
      'Cloud-top temp.': '~-178 °C',
      'Moons': '274 known (most of any planet)',
      'Atmosphere': '96% H₂, 3% He',
    },
    facts: [
      'Saturn is the least dense planet — it would float in water.',
      'Its rings span up to ~280,000 km wide but are only ~10 m to 1 km thick.',
      'Saturn has more confirmed moons than any other planet.',
      'Its largest moon, Titan, has a thick atmosphere and liquid-methane lakes.',
      'A hexagonal jet stream swirls around its north pole.',
    ],
  },
  {
    id: 'uranus', name: 'Uranus', type: 'Ice Giant',
    texture: 'textures/uranus.jpg', color: 0xa6e1e6,
    ring: { inner: 1.5, outer: 2.0, color: 0x9fb6c2, opacity: 0.35 },
    radiusEarth: 4.01, axialTilt: 97.77, rotationHours: -17.24,
    a: 19.18916464, e: 0.04725744, i: 0.77263783,
    om: 74.01692503, wbar: 170.95427630, L0: 313.23810451, periodDays: 30688.5,
    description:
      'Uranus is an ice giant that rotates on its side, with an axial tilt of ' +
      'nearly 98°. This extreme tilt gives it the most unusual seasons in the ' +
      'Solar System. Its pale blue-green colour comes from methane in its atmosphere.',
    info: {
      'Diameter': '50,724 km',
      'Mass': '8.68 × 10²⁵ kg (14.5 × Earth)',
      'Surface gravity': '8.87 m/s²',
      'Mean density': '1.27 g/cm³',
      'Distance from Sun': '2,871 million km (19.2 AU)',
      'Orbital period': '84 Earth years',
      'Rotation period': '17.2 hours (retrograde)',
      'Axial tilt': '97.77°',
      'Orbital velocity': '6.8 km/s',
      'Eccentricity': '0.047',
      'Orbital inclination': '0.77°',
      'Cloud-top temp.': '~-224 °C (coldest)',
      'Moons': '29 known',
      'Atmosphere': '83% H₂, 15% He, 2% CH₄',
    },
    facts: [
      'Uranus rotates on its side — it essentially rolls along its orbit.',
      'It was the first planet discovered with a telescope (1781, by William Herschel).',
      'Uranus has the coldest atmosphere of any planet (~ -224 °C).',
      'Its 29 moons are named after characters from Shakespeare and Alexander Pope.',
      'Each pole gets ~42 years of continuous sunlight, then 42 years of darkness.',
    ],
  },
  {
    id: 'neptune', name: 'Neptune', type: 'Ice Giant',
    texture: 'textures/neptune.jpg', color: 0x3b5bdb,
    radiusEarth: 3.88, axialTilt: 28.32, rotationHours: 16.11,
    a: 30.06992276, e: 0.00859048, i: 1.77004347,
    om: 131.78422574, wbar: 44.96476227, L0: -55.12002969, periodDays: 60182,
    description:
      'Neptune is the most distant planet — a cold, windy ice giant of deep ' +
      'blue. It hosts the fastest winds in the Solar System and was the first ' +
      'planet found by mathematical prediction rather than direct observation.',
    info: {
      'Diameter': '49,244 km',
      'Mass': '1.02 × 10²⁶ kg (17 × Earth)',
      'Surface gravity': '11.15 m/s²',
      'Mean density': '1.64 g/cm³',
      'Distance from Sun': '4,495 million km (30.1 AU)',
      'Orbital period': '164.8 Earth years',
      'Rotation period': '16.1 hours',
      'Axial tilt': '28.32°',
      'Orbital velocity': '5.4 km/s',
      'Eccentricity': '0.009',
      'Orbital inclination': '1.77°',
      'Cloud-top temp.': '~-214 °C',
      'Moons': '16 known',
      'Atmosphere': '80% H₂, 19% He, 1% CH₄',
    },
    facts: [
      'Neptune has the fastest winds in the Solar System — up to 2,100 km/h.',
      'It was discovered in 1846 through mathematical prediction.',
      'Neptune has completed only one orbit of the Sun since its discovery (in 2011).',
      'Its largest moon, Triton, orbits backwards and may be a captured dwarf planet.',
      'Like Uranus, it likely has a deep mantle of water, ammonia and methane ices.',
    ],
  },
  // -- Dwarf planet ----------------------------------------------------------
  {
    id: 'pluto', name: 'Pluto', type: 'Dwarf Planet',
    texture: 'textures/pluto.jpg', color: 0xccb7a3,   // NASA/New Horizons global colour map (PIA11707)
    radiusEarth: 0.186, axialTilt: 122.53, rotationHours: -153.29,
    a: 39.48211675, e: 0.24882730, i: 17.14001206,
    om: 110.30393684, wbar: 224.06891629, L0: 238.92903833, periodDays: 90560,
    isDwarf: true,
    description:
      'Pluto is the best-known dwarf planet, lying in the distant Kuiper Belt. ' +
      'Reclassified from "planet" in 2006, it is a complex world of nitrogen ' +
      'ice, mountains and a heart-shaped glacier revealed by NASA\'s New Horizons in 2015.',
    info: {
      'Diameter': '2,377 km',
      'Mass': '1.31 × 10²² kg (0.0022 × Earth)',
      'Surface gravity': '0.62 m/s²',
      'Mean density': '1.85 g/cm³',
      'Distance from Sun': '5,906 million km (39.5 AU avg)',
      'Orbital period': '248 Earth years',
      'Rotation period': '6.4 Earth days (retrograde)',
      'Axial tilt': '122.5°',
      'Orbital velocity': '4.7 km/s',
      'Eccentricity': '0.249',
      'Orbital inclination': '17.1°',
      'Surface temp.': '-233 °C to -223 °C',
      'Moons': '5 (Charon is the largest)',
      'Atmosphere': 'Thin N₂, CH₄, CO',
    },
    facts: [
      'Pluto was reclassified as a dwarf planet in 2006.',
      'Its orbit is so eccentric that it sometimes comes closer to the Sun than Neptune.',
      'Pluto and its moon Charon are tidally locked, always facing each other.',
      'Its heart-shaped region, Tombaugh Regio, is a vast glacier of nitrogen ice.',
      'It takes 248 Earth years for Pluto to orbit the Sun once.',
    ],
  },
  {
    id: 'ceres', name: 'Ceres', type: 'Dwarf Planet',
    texture: 'textures/ceres.jpg', color: 0x8c8377,
    radiusEarth: 0.0737, axialTilt: 4.0, rotationHours: 9.07417,
    // J2000 elements derived from JPL Small-Body Database (full precision).
    a: 2.76555260, e: 0.07969230, i: 10.588028,
    om: 80.248627, wbar: 153.542841, L0: 158.745564, periodDays: 1679.853,
    isDwarf: true,
    description:
      'Ceres is the largest object in the asteroid belt and the only dwarf ' +
      'planet in the inner Solar System. Holding about a quarter of the belt\'s ' +
      'total mass, it is an icy, rocky world with bright salt deposits and a ' +
      'likely briny layer beneath its crust. NASA\'s Dawn orbited it in 2015–18.',
    info: {
      'Diameter': '939 km',
      'Mass': '9.39 × 10²⁰ kg (0.00016 × Earth)',
      'Surface gravity': '0.27 m/s²',
      'Mean density': '2.16 g/cm³',
      'Distance from Sun': '414 million km (2.77 AU avg)',
      'Orbital period': '4.6 Earth years',
      'Rotation period': '9.07 hours',
      'Eccentricity': '0.079',
      'Orbital inclination': '10.6°',
      'Surface temp.': '~ -105 °C (avg)',
      'Moons': '0',
      'Location': 'Asteroid Belt',
      'Discovered': '1801 (G. Piazzi)',
    },
    facts: [
      'Ceres is the largest body in the asteroid belt and the closest dwarf planet to the Sun.',
      'Discovered in 1801, it was considered a planet for about 50 years.',
      'NASA\'s Dawn spacecraft orbited Ceres from 2015 to 2018.',
      'Bright salt deposits in Occator crater point to a subsurface briny reservoir.',
      'Ceres may hold more fresh water (as ice) than all of Earth\'s rivers and lakes.',
    ],
  },
  {
    id: 'haumea', name: 'Haumea', type: 'Dwarf Planet',
    texture: 'textures/haumea.jpg', color: 0xdfe3e6,
    radiusEarth: 0.1224, axialTilt: 0.0, rotationHours: 3.9154,
    a: 43.06029024, e: 0.19444301, i: 28.208474,
    om: 121.786056, wbar: 2.476603, L0: 192.007688, periodDays: 103208.117,
    isDwarf: true,
    description:
      'Haumea is a Kuiper Belt dwarf planet famous for its extreme egg-like ' +
      'shape, stretched by an ultra-fast ~4-hour spin. Coated in bright ' +
      'crystalline water ice, it has two moons and a ring, and is named after ' +
      'the Hawaiian goddess of childbirth.',
    info: {
      'Diameter': '~1,560 km (mean; ~2,100 km long axis)',
      'Mass': '4.0 × 10²¹ kg',
      'Mean density': '~2.0 g/cm³',
      'Distance from Sun': '6.45 billion km (43.1 AU avg)',
      'Orbital period': '283 Earth years',
      'Rotation period': '3.9 hours (one of the fastest)',
      'Eccentricity': '0.194',
      'Orbital inclination': '28.2°',
      'Surface temp.': '~ -240 °C',
      'Moons': '2 (Hiʻiaka & Namaka)',
      'Rings': 'Yes (found 2017)',
      'Location': 'Kuiper Belt',
    },
    facts: [
      'Haumea spins once every ~4 hours — so fast it is stretched nearly twice as long as it is wide.',
      'It was the first Kuiper Belt object found to have a ring system (2017).',
      'It has two known moons, Hiʻiaka and Namaka.',
      'Its surface is bright crystalline water ice.',
      'A giant impact likely created its spin, moons and a family of icy fragments.',
    ],
  },
  {
    id: 'makemake', name: 'Makemake', type: 'Dwarf Planet',
    texture: 'textures/makemake.jpg', color: 0xc97b50,
    radiusEarth: 0.1122, axialTilt: 0.0, rotationHours: 22.8266,
    a: 45.57093317, e: 0.15888900, i: 29.027856,
    om: 79.294834, wbar: 16.387107, L0: 155.390329, periodDays: 112364.807,
    isDwarf: true,
    description:
      'Makemake is a bright, reddish dwarf planet in the Kuiper Belt — the ' +
      'second-brightest after Pluto. Its surface is coated in frozen methane ' +
      'and ethane. It has one small, dark moon and is named after the creator ' +
      'god of the Rapa Nui people of Easter Island.',
    info: {
      'Diameter': '~1,430 km',
      'Mass': '~3.1 × 10²¹ kg',
      'Mean density': '~1.9 g/cm³',
      'Distance from Sun': '6.85 billion km (45.6 AU avg)',
      'Orbital period': '308 Earth years',
      'Rotation period': '22.8 hours',
      'Eccentricity': '0.159',
      'Orbital inclination': '29.0°',
      'Surface temp.': '~ -240 °C',
      'Moons': '1 (S/2015, "MK2")',
      'Location': 'Kuiper Belt',
      'Discovered': '2005',
    },
    facts: [
      'Makemake is the second-brightest Kuiper Belt object after Pluto.',
      'Its 2005 discovery (around Easter) helped trigger Pluto\'s reclassification.',
      'It is covered in frozen methane and ethane ices, giving it a reddish hue.',
      'A small, dark moon nicknamed "MK2" was found in 2016.',
      'Unlike Pluto, Makemake has almost no detectable atmosphere.',
    ],
  },
  {
    id: 'eris', name: 'Eris', type: 'Dwarf Planet',
    texture: 'textures/eris.jpg', color: 0xd8d8d0,
    radiusEarth: 0.1825, axialTilt: 0.0, rotationHours: 25.9,
    a: 67.93394688, e: 0.43823853, i: 43.925828,
    om: 36.004770, wbar: 186.799694, L0: 21.578056, periodDays: 204516.663,
    isDwarf: true,
    description:
      'Eris is the most massive known dwarf planet — slightly smaller than ' +
      'Pluto but about 27% heavier. It orbits far beyond Neptune in the ' +
      'scattered disc on a steeply tilted, very eccentric path. Its 2005 ' +
      'discovery directly led astronomers to define "dwarf planet".',
    info: {
      'Diameter': '2,326 km',
      'Mass': '1.65 × 10²² kg (most massive dwarf planet)',
      'Surface gravity': '0.82 m/s²',
      'Mean density': '2.4 g/cm³',
      'Distance from Sun': '10.2 billion km (67.9 AU avg)',
      'Orbital period': '560 Earth years',
      'Rotation period': '~25.9 hours',
      'Eccentricity': '0.44',
      'Orbital inclination': '43.9°',
      'Surface temp.': '~ -240 °C',
      'Moons': '1 (Dysnomia)',
      'Location': 'Scattered Disc',
    },
    facts: [
      'Eris is the most massive dwarf planet — about 27% heavier than Pluto.',
      'Its discovery in 2005 directly led to Pluto\'s reclassification in 2006.',
      'It is one of the most distant and reflective bodies in the Solar System.',
      'Its highly reflective surface is coated in methane ice.',
      'Its only moon, Dysnomia, is named after the daughter of the goddess Eris.',
    ],
  },
];

// Moons (simplified near-circular orbits around their parent). `dist` is the
// COMPRESSED display distance, in units of the parent's display radius (keeps
// the moon visible next to its planet). `aKm` is the REAL semi-major axis in km,
// used for the true-scale views. Period in Earth days.
export const MOONS = [
  { id: 'moon', name: 'Moon', parent: 'earth', texture: 'textures/moon.jpg',
    radiusEarth: 0.273, dist: 4.0, aKm: 384400, periodDays: 27.32, tilt: 6.68, color: 0xbbbbbb,
    info: { 'Diameter': '3,474 km', 'Distance from Earth': '384,400 km',
      'Orbital period': '27.3 days', 'Surface gravity': '1.62 m/s²',
      'Surface temp.': '-173 °C to 127 °C' },
    description: 'Earth\'s only natural satellite and the fifth-largest moon in the Solar System.',
    facts: ['The Moon is slowly moving away from Earth.',
      'It is tidally locked, so we always see the same face.',
      'Its gravity drives the ocean tides on Earth.'] },

  { id: 'io', name: 'Io', parent: 'jupiter', texture: 'textures/io.jpg',          // USGS Galileo/Voyager colour mosaic
    radiusEarth: 0.286, dist: 2.6, aKm: 421800, periodDays: 1.77, tint: 0xffffff, color: 0xf4e07a,
    info: { 'Diameter': '3,643 km', 'Orbital period': '1.77 days', 'Notable': 'Most volcanic body known' },
    description: 'Io is the most volcanically active world in the Solar System.',
    facts: ['Io has over 400 active volcanoes.', 'It is one of Jupiter\'s four Galilean moons.'] },
  { id: 'europa', name: 'Europa', parent: 'jupiter', texture: 'textures/europa.jpg',   // USGS Voyager/Galileo mosaic (greyscale, tinted icy)
    radiusEarth: 0.245, dist: 3.4, aKm: 671100, periodDays: 3.55, tint: 0xe7ddcb, color: 0xcdb999,
    info: { 'Diameter': '3,122 km', 'Orbital period': '3.55 days', 'Notable': 'Subsurface ocean' },
    description: 'Europa hides a salty liquid-water ocean beneath its icy crust — a prime target in the search for life.',
    facts: ['Europa may hold twice as much water as all of Earth\'s oceans.', 'Its surface is among the smoothest in the Solar System.'] },
  { id: 'ganymede', name: 'Ganymede', parent: 'jupiter', texture: 'textures/ganymede.jpg',  // USGS Kersten 2021 colour mosaic
    radiusEarth: 0.413, dist: 4.4, aKm: 1070400, periodDays: 7.15, tint: 0xffffff, color: 0x9c8e7a,
    info: { 'Diameter': '5,268 km', 'Orbital period': '7.15 days', 'Notable': 'Largest moon in the Solar System' },
    description: 'Ganymede is the largest moon in the Solar System — bigger than the planet Mercury.',
    facts: ['It is the only moon known to have its own magnetic field.', 'Ganymede is larger than Mercury.'] },
  { id: 'callisto', name: 'Callisto', parent: 'jupiter', texture: 'textures/callisto.jpg',  // USGS Voyager/Galileo mosaic (greyscale, tinted)
    radiusEarth: 0.378, dist: 5.6, aKm: 1882700, periodDays: 16.69, tint: 0x9a8f7f, color: 0x7a7268,
    info: { 'Diameter': '4,821 km', 'Orbital period': '16.69 days', 'Notable': 'Most heavily cratered body' },
    description: 'Callisto is the outermost Galilean moon and one of the most cratered objects known.',
    facts: ['Callisto\'s surface is among the oldest in the Solar System.', 'It may harbour a subsurface ocean.'] },

  { id: 'titan', name: 'Titan', parent: 'saturn', texture: 'textures/titan.jpg',   // USGS Cassini ISS global mosaic (greyscale, tinted haze)
    radiusEarth: 0.404, dist: 4.6, aKm: 1221870, periodDays: 15.95, tint: 0xd9a441, color: 0xd9a441,
    info: { 'Diameter': '5,150 km', 'Orbital period': '15.95 days', 'Notable': 'Thick atmosphere & methane lakes' },
    description: 'Titan is Saturn\'s largest moon — the only moon with a dense atmosphere and stable surface liquids.',
    facts: ['Titan has rivers, lakes and seas of liquid methane and ethane.', 'Its atmosphere is denser than Earth\'s.'] },

  { id: 'triton', name: 'Triton', parent: 'neptune', texture: 'textures/triton.jpg',   // USGS Voyager 2 colour mosaic (partial coverage)
    radiusEarth: 0.212, dist: 4.2, aKm: 354800, periodDays: -5.88, tint: 0xffffff, color: 0xc9c2d6,
    info: { 'Diameter': '2,707 km', 'Orbital period': '5.88 days (retrograde)', 'Notable': 'Geologically active, retrograde orbit' },
    description: 'Triton orbits Neptune backwards and is likely a captured Kuiper Belt object.',
    facts: ['Triton is one of the coldest objects in the Solar System (~ -235 °C).', 'It has active nitrogen geysers.'] },
];

// Interstellar spacecraft -----------------------------------------------------
// The Voyagers are NOT on bound Keplerian orbits — they fly the real, curved
// trajectory recorded by NASA/JPL: launched from Earth, gravity-assisted past the
// giant planets, then coasting out of the Solar System on hyperbolic escape
// paths. A single state vector propagated linearly cannot reproduce that (it
// never curves through the flybys, never starts at Earth, and exists before
// launch), so the full trajectory is tabulated in js/voyager_ephem.js as sampled
// HORIZONS state vectors and interpolated with cubic Hermite (see kepler.js,
// voyagerState). That table is keyed by the `id` below.
//
// HORIZONS frame: "Ecliptic of J2000.0", Sun-centered, AU & AU/day — the SAME
// frame kepler.js uses for the planets, so it maps into the scene with the
// identical (X, Z, −Y) convention. Shown only in the true-scale views, and
// hidden entirely before each craft's launch date.
export const VOYAGERS = [
  {
    id: 'voyager1', name: 'Voyager 1', type: 'Interstellar Probe',
    color: 0x9fd8ff, isSpacecraft: true,
    launchISO: '1977-09-05', interstellarISO: '2012-08-25',
    // Trajectory: VOYAGER_EPHEM.voyager1 (HORIZONS body -31). See voyager_ephem.js.
    description:
      "NASA's Voyager 1 is the most distant human-made object ever built. " +
      "Launched on 5 September 1977, it flew past Jupiter (1979) and Saturn " +
      "(1980) — its close look at Saturn's moon Titan flung it up and out of " +
      "the planetary plane. In August 2012 it crossed the heliopause, becoming " +
      "the first spacecraft to enter interstellar space. It is still tracked and " +
      "still returning data across more than a full light-day of distance.",
    facts: [
      'Voyager 1 is the farthest human-made object from Earth.',
      'It crossed into interstellar space in August 2012.',
      'It carries the Golden Record — sounds and images of life on Earth.',
      'Radio signals from it take well over a day to reach Earth.',
      'Its plutonium power source is expected to fade out in the 2030s.',
    ],
  },
  {
    id: 'voyager2', name: 'Voyager 2', type: 'Interstellar Probe',
    color: 0xffc46b, isSpacecraft: true,
    launchISO: '1977-08-20', interstellarISO: '2018-11-05',
    // Trajectory: VOYAGER_EPHEM.voyager2 (HORIZONS body -32). See voyager_ephem.js.
    description:
      "NASA's Voyager 2 is the only spacecraft to have visited all four giant " +
      "planets — Jupiter (1979), Saturn (1981), Uranus (1986) and Neptune (1989). " +
      "Its Neptune encounter bent it south, below the ecliptic. Launched on " +
      "20 August 1977 (a fortnight before its twin), it crossed the heliopause in " +
      "November 2018 to become the second probe in interstellar space, and " +
      "continues to operate on a dwindling nuclear power supply.",
    facts: [
      'Voyager 2 is the only probe to fly past Uranus and Neptune.',
      'It entered interstellar space in November 2018.',
      'It too carries a copy of the Golden Record.',
      'It travels slightly slower than Voyager 1 and on a southward heading.',
      'It has been operating continuously for over 48 years.',
    ],
  },
];

// Asteroid / Kuiper belt parameters (in AU; converted via the distance map).
export const BELTS = {
  asteroid: { innerAU: 2.1, outerAU: 3.3, count: 2200, thickness: 0.18, size: [0.04, 0.16] },
  kuiper:   { innerAU: 33,  outerAU: 50,  count: 2600, thickness: 1.4,  size: [0.05, 0.12] },
};

export const CREDITS =
  'Planetary & star textures © Solar System Scope (CC BY 4.0). ' +
  'Pluto & major-moon maps: NASA/JHUAPL/SwRI & USGS Astrogeology (public domain). ' +
  'Orbital elements: NASA/JPL (J2000.0). Voyager 3D model: NASA/VTAD (public domain). ' +
  'Voyager positions: NASA/JPL HORIZONS state vectors. Built with three.js.';
