#!/usr/bin/env python3
"""Generate js/eclipse_catalog.js from the NASA GSFC Five Millennium Canon
catalog pages (Espenak & Meeus). Build-time fetch -> committed module; the
app itself performs no network requests.

Times in the source are TD (Terrestrial Time) at greatest eclipse; each row
carries its own delta-T, which we subtract to store UTC ISO strings.

Usage:  python tools/fetch_eclipse_catalog.py
"""
import re
import urllib.request
from datetime import datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "js" / "eclipse_catalog.js"
YEARS = (2001, 2050)

MONTHS = {m: i + 1 for i, m in enumerate(
    ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
     "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])}


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    return urllib.request.urlopen(req, timeout=60).read().decode("utf8", "replace")


def strip_tags(html):
    return re.sub(r"<[^>]+>", "", html)


def parse_duration(token):
    m = re.match(r"(\d+)m(\d+)s", token)
    return int(m.group(1)) * 60 + int(m.group(2)) if m else None


def to_utc_iso(year, mon, day, td_hms, delta_t_s):
    td = datetime(year, mon, day, *[int(x) for x in td_hms.split(":")])
    utc = td - timedelta(seconds=delta_t_s)
    return utc.strftime("%Y-%m-%dT%H:%M:%SZ")


def parse_coord(tok):
    value = float(tok[:-1])
    return value if tok[-1] in "NE" else -value


def parse_solar():
    text = strip_tags(fetch("https://eclipse.gsfc.nasa.gov/SEcat5/SE2001-2100.html"))
    events = []
    for line in text.splitlines():
        if not re.match(r"^\s*\d{5}\s+\d{4} \w{3} \d{2}", line):
            continue
        tok = line.split()
        # [num, Y, Mon, D, TD, dT, lunaNum, saros, type, qle, gamma, mag,
        #  lat, lon, alt, width?, dur?]  — width/dur may be '-' or absent.
        year = int(tok[1])
        if not (YEARS[0] <= year <= YEARS[1]):
            continue
        kind = tok[8][0]
        if kind not in "TAHP":
            continue
        width = None
        dur = None
        for extra in tok[15:17]:
            if extra.isdigit():
                width = int(extra)
            elif re.match(r"\d+m\d+s", extra):
                dur = parse_duration(extra)
        events.append({
            "d": to_utc_iso(year, MONTHS[tok[2]], int(tok[3]), tok[4], int(tok[5])),
            "t": "S", "k": kind, "s": int(tok[7]),
            "g": float(tok[10]), "m": float(tok[11]),
            "lat": parse_coord(tok[12]), "lon": parse_coord(tok[13]),
            "w": width, "dur": dur,
        })
    return events


def parse_lunar():
    text = strip_tags(fetch("https://eclipse.gsfc.nasa.gov/LEcat5/LE2001-2100.html"))
    events = []
    for line in text.splitlines():
        if not re.match(r"^\s*\d{5}\s+\d{4} \w{3} \d{2}", line):
            continue
        tok = line.split()
        # [num, Y, Mon, D, TD, dT, lunaNum, saros, type, qle, gamma,
        #  penMag, umMag, penDurMin, parDurMin, totDurMin, lat, lon, ...]
        year = int(tok[1])
        if not (YEARS[0] <= year <= YEARS[1]):
            continue
        kind = tok[8][0]
        if kind not in "NPT":
            continue
        def minutes(v):
            try:
                return int(float(v) * 60)
            except ValueError:
                return None
        events.append({
            "d": to_utc_iso(year, MONTHS[tok[2]], int(tok[3]), tok[4], int(tok[5])),
            "t": "L", "k": kind, "s": int(tok[7]),
            "g": float(tok[10]), "m": float(tok[12]),
            "penMag": float(tok[11]),
            "dur": minutes(tok[15]) if kind == "T" else minutes(tok[14]),
        })
    return events


def js_value(v):
    if v is None:
        return "null"
    if isinstance(v, str):
        return f'"{v}"'
    return repr(v)


def main():
    events = parse_solar() + parse_lunar()
    events.sort(key=lambda e: e["d"])
    assert len(events) > 150, f"suspiciously few events: {len(events)}"
    # Sanity anchors straight from the canon.
    anchors = {e["d"][:10]: e for e in events}
    a = anchors.get("2024-04-08")
    assert a and a["k"] == "T" and abs(a["g"] - 0.3431) < 1e-4, a
    b = anchors.get("2027-08-02")
    assert b and b["k"] == "T" and abs(b["g"] - 0.1421) < 2e-3, b

    keys = ["d", "t", "k", "s", "g", "m", "lat", "lon", "w", "dur", "penMag"]
    rows = []
    for e in events:
        parts = [f"{k}:{js_value(e[k])}" for k in keys if k in e]
        rows.append("{" + ",".join(parts) + "}")
    body = (
        "// AUTO-GENERATED by tools/fetch_eclipse_catalog.py — DO NOT EDIT BY HAND.\n"
        "// Source: Fred Espenak & Jean Meeus, Five Millennium Canon of Solar\n"
        "// Eclipses (NASA TP-2006-214141) and of Lunar Eclipses (NASA\n"
        "// TP-2009-214172), via eclipse.gsfc.nasa.gov. NASA material is in the\n"
        "// public domain; citation: 'Eclipse Predictions by Fred Espenak, NASA/GSFC'.\n"
        "// d = UTC of greatest eclipse (converted from TD with the row's own dT);\n"
        "// t = S|L; k = T/A/H/P (solar) or T/P/N (lunar); s = saros; g = gamma;\n"
        "// m = magnitude (solar: eclipse, lunar: umbral); lat/lon/w/dur solar-only.\n"
        f"export const ECLIPSES = [\n  " + ",\n  ".join(rows) + ",\n];\n")
    OUT.write_text(body, encoding="utf8", newline="\n")
    solar = sum(1 for e in events if e["t"] == "S")
    print(f"Wrote {OUT}: {len(events)} events ({solar} solar, {len(events) - solar} lunar)")


if __name__ == "__main__":
    main()
