#!/usr/bin/env node
// Generate js/starcatalog.js from the Yale Bright Star Catalogue (BSC5,
// public domain, Harvard TDC mirror). Build-time fetch → committed module,
// following the fetch_voyager_ephem.py pattern: the app itself makes no
// network requests. Run: node tools/generate_starcatalog.mjs
import { writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gunzipSync } from 'node:zlib';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'js', 'starcatalog.js');
const SOURCE = 'http://tdc-www.harvard.edu/catalogs/bsc5.dat.gz';
const LIMIT_VMAG = 6.5;

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`BSC5 download failed: HTTP ${response.status}`);
const text = gunzipSync(Buffer.from(await response.arrayBuffer())).toString('latin1');

const rows = [];
for (const line of text.split('\n')) {
  if (line.length < 114) continue;
  const hr = Number(line.slice(0, 4).trim());
  const raH = Number(line.slice(75, 77));
  const raM = Number(line.slice(77, 79));
  const raS = Number(line.slice(79, 83));
  const deSign = line[83] === '-' ? -1 : 1;
  const deD = Number(line.slice(84, 86));
  const deM = Number(line.slice(86, 88));
  const deS = Number(line.slice(88, 90));
  const vmag = Number(line.slice(102, 107).trim());
  const bvRaw = line.slice(109, 114).trim();
  const bv = bvRaw === '' ? 0.65 : Number(bvRaw);   // missing B−V → solar colour
  if (!Number.isFinite(hr) || !Number.isFinite(raH) || !Number.isFinite(vmag)) continue;
  if (vmag > LIMIT_VMAG) continue;
  const raDeg = (raH + raM / 60 + raS / 3600) * 15;
  const decDeg = deSign * (deD + deM / 60 + deS / 3600);
  if (!Number.isFinite(raDeg) || !Number.isFinite(decDeg) || !Number.isFinite(bv)) continue;
  rows.push([hr, +raDeg.toFixed(4), +decDeg.toFixed(4), vmag, +bv.toFixed(3)]);
}
if (rows.length < 8000) throw new Error(`suspiciously few stars parsed: ${rows.length}`);

const flat = rows.flat();
const body = `// AUTO-GENERATED by tools/generate_starcatalog.mjs — DO NOT EDIT BY HAND.
// Yale Bright Star Catalogue (BSC5, public domain), V <= ${LIMIT_VMAG}, J2000.
// ${rows.length} stars; stride [HR, RA(deg), Dec(deg), Vmag, B−V].
export const STAR_STRIDE = 5;
export const STAR_COUNT = ${rows.length};
export const STARS = new Float64Array([${flat.join(',')}]);
`;
await writeFile(OUT, body);
console.log(`Wrote ${OUT}: ${rows.length} stars (${(body.length / 1024).toFixed(0)} KB)`);
const sirius = rows.find(r => r[0] === 2491);
console.log('Sirius check:', sirius);
