// Regenerates js/offline_manifest.js — the file list the "offline pack"
// button prefetches so the whole app (2K assets) works without a network.
// Run after adding/removing assets:  node tools/generate_offline_manifest.mjs
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));

const files = [];
function walk(dir, filter = () => true) {
  for (const name of readdirSync(join(root, dir))) {
    const rel = `${dir}/${name}`;
    const st = statSync(join(root, rel));
    if (st.isDirectory()) continue;               // each dir is listed explicitly
    if (filter(name)) files.push({ path: rel, bytes: st.size });
  }
}

files.push({ path: 'index.html', bytes: statSync(join(root, 'index.html')).size });
files.push({ path: 'manifest.webmanifest', bytes: statSync(join(root, 'manifest.webmanifest')).size });
walk('css');
walk('fonts');
walk('icons');
walk('js');
walk('lib');
walk('lib/addons');
walk('lib/addons/controls');
walk('lib/addons/loaders');
walk('lib/addons/postprocessing');
walk('lib/addons/renderers');
walk('lib/addons/shaders');
walk('lib/addons/utils');
walk('models');
walk('textures', (n) => /\.(jpg|png)$/.test(n));            // 2K set only — no 8k/
walk('textures/blackhole', (n) => /\.(jpg|png|bin|json)$/.test(n));

const total = files.reduce((sum, f) => sum + f.bytes, 0);
const list = files.map((f) => `  '${f.path}',`).join('\n');
writeFileSync(join(root, 'js/offline_manifest.js'),
  `// GENERATED by tools/generate_offline_manifest.mjs — do not edit by hand.
// Every file the app needs to run fully offline at 2K quality.
export const OFFLINE_ASSETS = [
${list}
];
export const OFFLINE_TOTAL_BYTES = ${total};
`);
console.log(`js/offline_manifest.js: ${files.length} files, ${(total / 1048576).toFixed(1)} MB`);
